name: viewducts
description: Viewducts Marketplace.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+9

environment:
  sdk: ">=2.17.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  alphabet_scroll_view: ^0.3.2
  cupertino_icons: ^1.0.2
  firebase_remote_config: 
  fpdart: ^0.4.0
  flutter_email_sender: 
  carousel_slider: ^4.2.1
  file_selector: ^0.9.2
  fast_contacts: ^1.1.1
  get: ^4.6.5
  contacts_service: ^0.6.3
  audioplayers: ^1.1.1
  azlistview: ^2.0.0
  cupertino_list_tile: ^0.2.1
  numeral:
  rating_dialog: ^2.0.4
  #awesome_notifications_fcm: 
  #flutter_local_notifications: 
  image_gallery_saver: 
  #awesome_notifications: ^0.7.4+1 
  dart_appwrite: ^7.1.0
  mobx: ^2.0.6+1
  flutter_riverpod: ^2.1.3
  flutter_mobx: ^2.0.4
  like_button: ^2.0.4
  data_connection_checker_tv: ^0.3.5-nullsafety
  flutterfire_ui: ^0.4.1
  webview_windows: ^0.2.0
  #websafe_svg: ^2.1.2
  universal_html: ^2.0.8
  badges: ^2.0.2
  file_saver: ^0.1.1
  dio: ^4.0.6
  flutter_sound_lite: ^8.5.0
  flutter_svg:  
  melos: ^2.7.1
  firebase_auth: 
  firebase_database: 
  status_view: ^0.0.2
  firebase_analytics: 
  data_table_2: ^2.0.3
  firebase_core:
  fl_chart: ^0.55.0
  flutter_sim_country_code: ^0.1.2
  #modal_bottom_sheet:
  cloud_firestore: 
  firebase_storage: 
  cached_network_image:
  custom_picker: ^0.0.4
  drop_down_list: ^0.0.2
  #firebase_crashlytics:
  flutter_easyloading: ^3.0.3
  chat_bubbles: ^1.2.0
  slide_to_act: ^2.0.1
  skeletons: ^0.0.3
  empty_widget: ^0.0.5
  status_alert: ^1.0.0
  awesome_dialog: ^2.1.2
  #flutter_paystack: ^1.0.5+1
  # spotlight_carousel: ^0.1.1
  # Emojies
  #video_compress: ^3.1.0
  loading_indicator: ^3.1.0
  text_editor: ^0.7.0
  push: ^0.1.3
  uni_links: ^0.5.1
  flutter_image_compress: ^1.1.0
  video_player: ^2.0.0
  flutter_paystack_payment: ^0.1.2+6
  filesize: ^2.0.1
  url_strategy: ^0.2.0
  go_router: ^5.0.5
  focused_menu: ^1.0.5
  logger: ^1.0.0
  firebase_database_web: 
  swipe_to: ^1.0.2
  csc_picker: ^0.2.6
  #light_compressor: ^0.0.5
  video_thumbnail: ^0.5.0
  flutter_luban: ^0.1.11
  #jitsi_meet: ^4.0.0
  flutter_app_badger: ^1.1.2
  #awesome_dropdown: ^0.0.4
  selectable_container: ^1.0.2
  #flutter_background_geolocation: ^4.3.4
  #flutter_widgets: 
  # video_trimmer:
  #better_player: ^0.0.32
  # video_player_platform_interface: ^2.1.1
  liquid_swipe:
  quiver: ^3.0.0-nullsafety
  quick_actions: ^1.0.0
  firebase_dynamic_links: ^5.0.11
  syncfusion_flutter_charts: ^20.1.57
  syncfusion_flutter_datepicker: ^20.1.57
  syncfusion_flutter_sliders: ^20.1.57
  syncfusion_flutter_calendar: ^20.1.57
  syncfusion_flutter_core: ^20.1.57
  emoji_picker_flutter: 
  direct_select: ^2.0.0
  pdf: ^3.1.0
  flutter_markdown: ^0.6.12
  appwrite: ^8.1.0
  rename:
  rxdart:
  infinite_scroll_pagination: ^3.2.0
  flutter_linkify: ^5.0.2
  blobs: ^2.0.0
  device_info_plus: ^4.1.2
  share_plus: ^4.1.0
  custom_pop_up_menu: ^1.2.4
  seo_renderer: ^0.6.0
 # open_file: 
#  search_widget: ^1.0.2
  #advanced_search: ^2.0.0
  #flutter_keyboard_visibility: ^5.1.1
  #firebase_performance:
  fluttertoast: ^8.0.8
  expandable:
  #flutter_paystack: ^1.0.5+1
  timeago: ^3.1.0
  uuid: 
  emojis: ^0.9.9
  animated_custom_dropdown: ^1.2.2
  flutter_aws_s3_client: ^0.6.0
  http: 
  minio: ^3.5.0
  flutter_native_splash: 
  file_picker: 
  google_sign_in: ^5.2.1
  image_picker: ^0.8.5+3
  #package_info: 
  aws3_bucket: ^0.0.6
  shared_preferences: ^2.0.11
  firebase_messaging: 
  url_launcher: ^6.1.6
  #share: ^2.0.4
  google_fonts: 
  aws_s3_upload: ^1.4.0
  bot_toast: ^4.0.1
  diacritic: ^0.1.1
  sqflite: ^2.2.0+3
  sentry:
  native_video_view: ^1.0.5
  image_cropper: ^2.0.3
  #contacts_service: 
  permission_handler: ^10.0.0
  #scoped_model: ^2.0.0-nullsafty
  local_auth:
  crypto: ^3.0.1
  encrypt: ^5.0.0
  keyboard_dismisser: 
  #storage_path: ^0.2.0 
  localstorage: 
  path_provider: ^2.0.11
  flutter_cache_manager: ^3.1.2
  photo_view: ^0.14.0
  lottie: 
  mime: ^1.0.1
  ntp:
  story_view: ^0.13.2
  connectivity_plus:
  #data_connection_checker: ^0.3.4
  cached_memory_image: ^1.3.1
  animations:
  
  flutter_staggered_grid_view: ^0.6.1
  launch_review: ^3.0.1
  flutter_secure_storage:
  flutter_localizations:
      sdk: flutter
  intl: ^0.17.0
  flutter_hooks: ^0.18.5+1
  firebase_crashlytics: 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.10.0
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true"
  image_path: "assets/app_logo.png"
  web:
    generate: true
    image_path: "assets/app_logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/app_logo.png"
    icon_size: 48 # min:48, max:256, default: 48
     
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/
    - assets/flags/
    - assets/lottie/
    - assets/images/
    - assets/policy/
  fonts:
    - family: TwitterIcon
      fonts:
        - asset: assets/fonts/icons.ttf
    - family: HelveticaNeue
      fonts:
        - asset: assets/fonts/HelveticaNeue.ttf
        - asset: assets/fonts/HelveticaNeue400.ttf
          weight: 400
        - asset: assets/fonts/HelveticaNeue500.ttf
          weight: 500
        - asset: assets/fonts/HelveticaNeue600.ttf
          weight: 600
        - asset: assets/fonts/HelveticaNeue700.ttf
          weight: 700
        - asset: assets/fonts/HelveticaNeue800.ttf
          weight: 800
        - asset: assets/fonts/HelveticaNeue900.ttf
          weight: 900
        - asset: assets/fonts/HelveticaNeueIt.ttf
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Black.ttf
        - asset: assets/fonts/Roboto-BlackItalic.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 500
        - asset: assets/fonts/Roboto-BoldItalic.ttf
          weight: 600
        - asset: assets/fonts/Roboto-Italic.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 800
        - asset: assets/fonts/Roboto-LightItalic.ttf
          style: italic
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 700
        - asset: assets/fonts/Roboto-MediumItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
