// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-3FYWQIjcQA6tw8YJtqE8hQiYaEBWKZU',
    appId: '1:649577760677:web:71cc1ebde88920c26aca4c',
    messagingSenderId: '649577760677',
    projectId: 'viewducts-backend',
    authDomain: 'viewducts-backend.firebaseapp.com',
    databaseURL: 'https://viewducts-backend.firebaseio.com',
    storageBucket: 'viewducts-backend.appspot.com',
    measurementId: 'G-QKZ4QDCVGS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtCr1SgjQTwcj51WlP9Jlh7LlGVNkyh4k',
    appId: '1:649577760677:android:4956a0c31a0432886aca4c',
    messagingSenderId: '649577760677',
    projectId: 'viewducts-backend',
    databaseURL: 'https://viewducts-backend.firebaseio.com',
    storageBucket: 'viewducts-backend.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRH6s2rkYlqB1ORytpaxgh5ogH99DsqJQ',
    appId: '1:649577760677:ios:da1e69fb0a33dd906aca4c',
    messagingSenderId: '649577760677',
    projectId: 'viewducts-backend',
    databaseURL: 'https://viewducts-backend.firebaseio.com',
    storageBucket: 'viewducts-backend.appspot.com',
    androidClientId: '649577760677-g78l7nvt343223gkd5m0bjeo9rshnme3.apps.googleusercontent.com',
    iosClientId: '649577760677-pj3g1duq4i22f8qidka89hbglm1d9f1c.apps.googleusercontent.com',
    iosBundleId: 'com.viewducts.viewducts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRH6s2rkYlqB1ORytpaxgh5ogH99DsqJQ',
    appId: '1:649577760677:ios:da1e69fb0a33dd906aca4c',
    messagingSenderId: '649577760677',
    projectId: 'viewducts-backend',
    databaseURL: 'https://viewducts-backend.firebaseio.com',
    storageBucket: 'viewducts-backend.appspot.com',
    androidClientId: '649577760677-g78l7nvt343223gkd5m0bjeo9rshnme3.apps.googleusercontent.com',
    iosClientId: '649577760677-pj3g1duq4i22f8qidka89hbglm1d9f1c.apps.googleusercontent.com',
    iosBundleId: 'com.viewducts.viewducts',
  );
}
